version: 2
updates:
  # JS.
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily
      timezone: Europe/London
    assignees:
      - "revett"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Go.
  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   target-branch: "main"
  #   schedule:
  #     interval: daily
  #     timezone: Europe/London
  #   assignees:
  #     - "revett"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-patch"]
