name: Docker / Integration Test

on:
  workflow_run:
    workflows: ["Docker / Build"]
    types:
      - completed

jobs:
  job:
    name: Run
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: daylang
          path: .

      - name: Load Docker image
        run: docker load < daylang.tar

      - name: Run Docker container
        run: |
          docker run -d -p 5173:5173 --name daylang daylang:${{ github.sha }}
          sleep 5

      - name: Check status endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5173/status)
          if [ $response -ne 200 ]; then
            echo "status endpoint returned $response, expected 200"
            exit 1
          fi

          content=$(curl -s http://localhost:5173/status)
          if ! echo $content | jq -e '.status == "ok"' > /dev/null; then
            echo "status is not 'ok'"
            exit 1
          fi

          if ! echo $content | jq -e '.version' > /dev/null; then
            echo "version is missing"
            exit 1
          fi

          echo "status endpoint check passed"

      - name: Clean up
        run: docker stop daylang
