name: Docker / Build & Test

on: [push]

jobs:
  job:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: daylang:${{ github.sha }}

      - name: Run Docker container
        run: |
          docker run -d -p 5174:5174 --name daylang daylang:${{ github.sha }}
          sleep 5

      - name: Check status endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5174/status)
          if [ $response -ne 200 ]; then
            echo "status endpoint returned $response, expected 200"
            exit 1
          fi

          content=$(curl -s http://localhost:5174/status)
          if ! echo $content | jq -e '.status == "ok"' > /dev/null; then
            echo "status is not 'ok'"
            exit 1
          fi

          if ! echo $content | jq -e '.version' > /dev/null; then
            echo "version is missing"
            exit 1
          fi

          echo "status endpoint check passed"

      - name: Clean up
        run: docker stop daylang
